/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package room.booking.system;


import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;



public class Home extends javax.swing.JFrame {


    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
         
        setSize(1000, 650); 
       
     

        setLocationRelativeTo(null);

        

          // Add mouse listeners to cards
        setupCardListeners();
        

        
    }
    
    
   
        /**
     * Setup mouse listeners for navigation cards
     */
    private void setupCardListeners() {
        // Set cursor to hand for all cards
        CustomerCard.setCursor(new Cursor(Cursor.HAND_CURSOR));
        RoomCard.setCursor(new Cursor(Cursor.HAND_CURSOR));
        BookingCard.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Bookings card
        GeneralCard.setCursor(new Cursor(Cursor.HAND_CURSOR)); // General card
        
        // Add mouse listener for Customers card
        CustomerCard.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                openCustomerForm();
            }
            
     
        });
        
        // Add mouse listener for Rooms card
        RoomCard.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                openRoomForm();
            }
          
        });
        
        // Add mouse listener for Bookings card
        BookingCard.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                openBookingForm();
            }
          
        });
        
        // Add mouse listener for General card
        GeneralCard.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                openGeneralScreen();
            }
         
        });
    }
    
    /**
     * Open the Customer Management Screen
     */
    private void openCustomerForm() {
        CustomerForm customerForm = new CustomerForm();
        customerForm.setVisible(true);
        this.dispose();
    }
    
    /**
     * Open the Room Management Screen
     */
    private void openRoomForm() {
        RoomForm roomForm = new RoomForm();
            roomForm.setVisible(true);
        this.dispose();
    }
    
    /**
     * Open the Booking Management Screen
     */
    private void openBookingForm() {
        BookingForm bookingForm = new BookingForm();
         bookingForm.setVisible(true);
        this.dispose();
    }
    
    /**
     * Open the General Screen for check-in/check-out
     */
    private void openGeneralScreen() {
        GeneralScreen generalScreen = new GeneralScreen();
        generalScreen.setVisible(true);
        this.dispose();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        RoomCard = new javax.swing.JPanel();
        roomTitle = new javax.swing.JLabel();
        roomDesc = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        roomIcon = new javax.swing.JLabel();
        CustomerCard = new javax.swing.JPanel();
        customerTitle = new javax.swing.JLabel();
        customerDesc = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        customerIcon = new javax.swing.JLabel();
        BookingCard = new javax.swing.JPanel();
        bookingDesc = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        bookingIcon = new javax.swing.JLabel();
        bookingTitle = new javax.swing.JLabel();
        GeneralCard = new javax.swing.JPanel();
        generalTitle = new javax.swing.JLabel();
        generalDesc = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        generalIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Room Booking System");
        setMinimumSize(new java.awt.Dimension(1120, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(0, 0, 204));
        headerPanel.setFocusable(false);
        headerPanel.setMaximumSize(new java.awt.Dimension(13334, 80));
        headerPanel.setPreferredSize(new java.awt.Dimension(1200, 80));

        titleLabel.setBackground(new java.awt.Color(0, 0, 204));
        titleLabel.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Room Booking System");
        titleLabel.setMaximumSize(new java.awt.Dimension(1000, 50));
        titleLabel.setMinimumSize(new java.awt.Dimension(1000, 50));
        titleLabel.setPreferredSize(new java.awt.Dimension(1120, 50));

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 60));

        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RoomCard.setBackground(new java.awt.Color(255, 102, 255));
        RoomCard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RoomCard.setPreferredSize(new java.awt.Dimension(300, 180));

        roomTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        roomTitle.setForeground(new java.awt.Color(204, 0, 204));
        roomTitle.setText("Rooms");
        roomTitle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        roomDesc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        roomDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomDesc.setText("Add New Rooms");
        roomDesc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel5.setBackground(new java.awt.Color(204, 0, 204));

        roomIcon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        roomIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/room/icons/icons8-home-50.png"))); // NOI18N
        roomIcon.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roomIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roomIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout RoomCardLayout = new javax.swing.GroupLayout(RoomCard);
        RoomCard.setLayout(RoomCardLayout);
        RoomCardLayout.setHorizontalGroup(
            RoomCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomCardLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(RoomCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RoomCardLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(RoomCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomDesc)
                            .addComponent(roomTitle))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RoomCardLayout.setVerticalGroup(
            RoomCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomCardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomDesc)
                .addGap(22, 22, 22))
        );

        jPanel1.add(RoomCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 260, 200));

        CustomerCard.setBackground(new java.awt.Color(102, 255, 102));
        CustomerCard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        customerTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        customerTitle.setForeground(new java.awt.Color(0, 102, 0));
        customerTitle.setText("Customers");
        customerTitle.setVerifyInputWhenFocusTarget(false);
        customerTitle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        customerDesc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        customerDesc.setText("Register Your Customer");
        customerDesc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel8.setBackground(new java.awt.Color(0, 153, 0));

        customerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/room/icons/icons8-user-80.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        customerIcon.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout CustomerCardLayout = new javax.swing.GroupLayout(CustomerCard);
        CustomerCard.setLayout(CustomerCardLayout);
        CustomerCardLayout.setHorizontalGroup(
            CustomerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerCardLayout.createSequentialGroup()
                .addGroup(CustomerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerCardLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(CustomerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerTitle)
                            .addComponent(customerDesc)))
                    .addGroup(CustomerCardLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CustomerCardLayout.setVerticalGroup(
            CustomerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerCardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerDesc)
                .addGap(29, 29, 29))
        );

        jPanel1.add(CustomerCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 260, 200));
        CustomerCard.getAccessibleContext().setAccessibleName("");

        BookingCard.setBackground(new java.awt.Color(51, 51, 255));
        BookingCard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BookingCard.setPreferredSize(new java.awt.Dimension(300, 180));

        bookingDesc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bookingDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookingDesc.setText("Manage Bookings");

        jPanel6.setBackground(new java.awt.Color(0, 0, 153));

        bookingIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/room/icons/icons8-calendar-48.png"))); // NOI18N
        bookingIcon.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookingIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookingIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bookingTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        bookingTitle.setForeground(new java.awt.Color(0, 0, 204));
        bookingTitle.setText("Bookings");

        javax.swing.GroupLayout BookingCardLayout = new javax.swing.GroupLayout(BookingCard);
        BookingCard.setLayout(BookingCardLayout);
        BookingCardLayout.setHorizontalGroup(
            BookingCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingCardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BookingCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookingDesc)
                    .addComponent(bookingTitle))
                .addGap(68, 68, 68))
            .addGroup(BookingCardLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BookingCardLayout.setVerticalGroup(
            BookingCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingCardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookingDesc)
                .addGap(19, 19, 19))
        );

        jPanel1.add(BookingCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 260, 200));

        GeneralCard.setBackground(new java.awt.Color(255, 102, 51));
        GeneralCard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GeneralCard.setPreferredSize(new java.awt.Dimension(300, 180));

        generalTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        generalTitle.setForeground(new java.awt.Color(153, 0, 0));
        generalTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generalTitle.setText("General");

        generalDesc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        generalDesc.setText("Manage Your Database");

        jPanel7.setBackground(new java.awt.Color(255, 102, 0));

        generalIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generalIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/room/icons/icons8-check-in-64.png"))); // NOI18N
        generalIcon.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generalIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generalIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        generalIcon.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout GeneralCardLayout = new javax.swing.GroupLayout(GeneralCard);
        GeneralCard.setLayout(GeneralCardLayout);
        GeneralCardLayout.setHorizontalGroup(
            GeneralCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralCardLayout.createSequentialGroup()
                .addGroup(GeneralCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneralCardLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GeneralCardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(generalTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralCardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(generalDesc)
                .addGap(67, 67, 67))
        );
        GeneralCardLayout.setVerticalGroup(
            GeneralCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralCardLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalDesc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(GeneralCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 260, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/room/icons/3.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookingCard;
    private javax.swing.JPanel CustomerCard;
    private javax.swing.JPanel GeneralCard;
    private javax.swing.JPanel RoomCard;
    private javax.swing.JLabel bookingDesc;
    private javax.swing.JLabel bookingIcon;
    private javax.swing.JLabel bookingTitle;
    private javax.swing.JLabel customerDesc;
    private javax.swing.JLabel customerIcon;
    private javax.swing.JLabel customerTitle;
    private javax.swing.JLabel generalDesc;
    private javax.swing.JLabel generalIcon;
    private javax.swing.JLabel generalTitle;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel roomDesc;
    private javax.swing.JLabel roomIcon;
    private javax.swing.JLabel roomTitle;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
